version: '3.8'

services:
  app:
    build:
      context: .
      target: deps # Use the deps stage for development
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/edtracts
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=edtracts

volumes:
  mongodb_data: 